apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cicd-dr-secondary-tyoko
  region: ap-northeast-1
managedNodeGroups:
  - name: manage
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    ssh:
      publicKeyName: ssupp-tyoko
  - name: web-server
    instanceType: t3.medium
    desiredCapacity: 6
    privateNetworking: true
    ssh:
      publicKeyName: ssupp-tyoko
  - name: app-server
    instanceType: t3.medium
    desiredCapacity: 6
    privateNetworking: true
    ssh:
      publicKeyName: ssupp-tyoko
